# Numpy_Assignment_2::

# Question:1

# Convert a 1D array to a 2D array with 2 rows?

# Desired output:

array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [11]:
import numpy as np
arr = np.arange(10)
arr= arr.reshape(2, len(arr) //2)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Question:2

# How to stack two arrays vertically?

# Desired Output::

array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [16]:
arr1 = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2 = np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Question:3

# How to stack two arrays horizontally?

# Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [18]:
arr1 = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2 = np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Question:4

# How to convert an array of arrays into a flat 1d array?


# Desired Output::


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [19]:
array = np.asarray([[0,1,2,3,4],[5,6,7,8,9]])
array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Question:5

# How to Convert higher dimension into one dimension?

# Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])



In [21]:
array = np.asarray([[[0,1,2,3,4],[5,6,7,8,9]]])  # 3dimension array
array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Question:6

# Convert one dimension to higher dimension?


# Desired Output::

array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])


In [31]:
array = np.asarray([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]).reshape(5,3)
array


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Question:7

# Create 5x5 an array and find the square of an array?

In [36]:
array = np.arange(25).reshape(5,5)
print("array :",array)
print("-------------------------")
print("square :",np.square(array))

array : [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
-------------------------
square : [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


# Question:8

# Create 5x6 an array and find the mean?

In [40]:
array = np.arange(30).reshape(5,6)
print("array :",array)
print("-------------------------")
print("mean :",np.mean(array))

array : [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
-------------------------
mean : 14.5


# Question:9

# Find the standard deviation of the previous array in Q8?

In [42]:
print("array:",array)
print("---------------------------")
print("standard deviation :",np.std(array))

array: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
---------------------------
standard deviation : 8.65544144839919


# Question:10

# Find the transpose of the previous array in Q8?

In [43]:
print("array:",array)
print("---------------------------")
print("transpose :",np.transpose(array))

array: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
---------------------------
transpose : [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


# Question:11

# Find the transpose of the previous array in Q8?

In [5]:
import numpy as np
print("Original: ", array)
print("Transpose: ", np.transpose(array))

Original:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Transpose:  [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


# Question:12

# Create a 4x4 an array and find the sum of diagonal elements?

In [46]:
array = np.arange(16).reshape(4,4)
diagonal_elements=np.trace(array)
diagonal_elements

30

# Question:13

# Find the determinant of the previous array in Q12?

In [48]:
np.linalg.det(array)

0.0

# Question:14


# Find the 5th and 95th percentile of an array?

In [49]:
array = np.arange(100).reshape(10,10)
print("5th percentile  :",np.percentile(array,5))
print("95th percentile :",np.percentile(array,95))

5th percentile  : 4.95
95th percentile : 94.05


# Question:15


# How to find if a given array has any null values?

In [50]:
arr = np.arange(100).reshape(10, 10) # --> Does not have null
arr_has_null = np.asarray([[[1, 2, 3, 4, None], [5, 6, 7, 8]]]) # --> Has null

has_null = lambda arr: print("Array has null values") if None in arr else print("Array does not have any null values")

has_null(arr)

Array does not have any null values


C:\Users\Zain Ali\anaconda3\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
